services:
  # The "One Link" Gateway (Frontend + Proxy)
  frontend:
    build: .
    restart: unless-stopped
    # Ports removed to avoid host conflict with Coolify proxy


  # The Streaming Backend (Hidden behind the Proxy)
  icecast:
    image: moul/icecast
    restart: unless-stopped
    # We don't expose 8000 to the public anymore! 
    # Nginx handles the traffic.
    environment:
      - ICECAST_SOURCE_PASSWORD=dataq123
      - ICECAST_ADMIN_PASSWORD=dataq123
      - ICECAST_PASSWORD=dataq123
