services:
  # The "One Link" Gateway (Frontend + Proxy)
  frontend:
    build: .
    restart: unless-stopped

  # The Streaming Backend
  icecast:
    image: moul/icecast
    restart: unless-stopped
    environment:
      - ICECAST_SOURCE_PASSWORD=dataq123
      - ICECAST_ADMIN_PASSWORD=dataq123
      - ICECAST_PASSWORD=dataq123

  # The Audio Bridge (WebSocket -> Icecast)
  bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    restart: unless-stopped
    depends_on:
      - icecast
