server {
    listen 80;
    server_name localhost;

    # The Website (Frontend)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # WHIP WebRTC Ingestion proxy
    location ~ ^/whip/(.*)$ {
        proxy_buffering off;
        proxy_pass http://mediamtx:8889/$1/whip;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WHEP WebRTC Egress proxy
    location ~ ^/whep/(.*)$ {
        proxy_buffering off;
        proxy_pass http://mediamtx:8889/$1/whep;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # MediaMTX Paths list API
    location /api/paths {
        proxy_pass http://mediamtx:9997/v3/paths/list;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
