server {
    listen 80;
    server_name localhost;

    # The Website (Frontend)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # WHIP WebRTC Ingestion proxy
    location ~ ^/(.*)/whip(.*)$ {
        resolver 127.0.0.11 valid=30s;
        set $mediamtx_whip mediamtx;
        proxy_buffering off;
        proxy_pass http://$mediamtx_whip:8889/$1/whip$2;
        proxy_set_header Authorization "";
        proxy_hide_header WWW-Authenticate;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WHEP WebRTC Egress proxy
    location ~ ^/(.*)/whep(.*)$ {
        resolver 127.0.0.11 valid=30s;
        set $mediamtx_whep mediamtx;
        proxy_buffering off;
        proxy_pass http://$mediamtx_whep:8889/$1/whep$2;
        proxy_set_header Authorization "";
        proxy_hide_header WWW-Authenticate;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # MediaMTX Paths list API
    location /api/paths {
        resolver 127.0.0.11 valid=30s;
        set $mediamtx_api mediamtx;
        proxy_pass http://$mediamtx_api:9997/v3/paths/list;
        proxy_set_header Authorization "";
        proxy_hide_header WWW-Authenticate;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
